### ISSUE TITLE
Ability to add control points while in edit mode

### ISSUE THREAD

**Issue by ssedai026** [ilfrich/annotator#6]
- Allow user to add new control points between existing control points when polygon annotation edit mode.

**Comment by ilfrich** [comment]
I'm now adding the point in between the **2 closest control points**.
An improvement would be to find the closest line between 2 points and add it between these. The current behaviour can lead to points being inserted before or after the gap you clicked on.

@ssedai026 Please let me know, if the current behaviour is not productive and I'll have another crack at it and find the closest points relative to the lines in between.
