### ISSUE TITLE
Ability to download the annotation types as json file

### ISSUE THREAD

**Issue by ssedai026** [ilfrich/annotator#7]

**Comment by ilfrich** [comment]
Discussed this offline and came to conclusion that the best way is to have a project setting import/export, which would export the annotation types and their colours (for now), but can be extended in the future to transfer other settings as well.

This allows larger teams to work across individual applications by using the same types of annotations, which makes aggregation of the annotation much easier.

On import I will run a script that checks for existing annotation types and allows the user to transfer their existing annotations to one of the imported ones or create a new type for legacy annotations (before import). Other existing annotation types will be purged.

**Comment by ilfrich** [comment]
@ssedai026 I've added the export feature right next to the annotation types list (configuration on project level).
Right beneath it you can also import an existing annotator-settings-<project>.json file to import the exact labels and colours of the annotation types. If the user has existing annotation types, s/he'll be asked what to do with them. I've built a little dialogue to handle that. Hope it is self-explanatory enough. If not, please let me know and I see that I can make it clearer.

_Latest Docker image pushed as well_
